# Netlify Configuration
[build]
  # Comando de build
  command = "npm run build"
  
  # Directorio de salida
  publish = "dist"
  
  # Variables de entorno para el build
  [build.environment]
    NODE_VERSION = "20"

# Redirects para SPA (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad básica
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Headers de seguridad adicionales
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Permitted-Cross-Domain-Policies = "none"
    
    # CORS Headers para Firebase (Chrome requiere dominio específico)
    Access-Control-Allow-Origin = "https://vocal-baklava-c94c36.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Allow-Credentials = "true"
    
    # Content Security Policy (configuración completa y segura para Firebase, reCAPTCHA, EmailJS y Google Fonts)
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://*.firebaseapp.com https://*.googleapis.com https://*.gstatic.com https://www.google.com https://apis.google.com https://www.gstatic.com https://*.firebaseio.com https://firestore.googleapis.com wss://firestore.googleapis.com https://api.emailjs.com;
      img-src 'self' data: https: blob: https://www.google.com https://www.gstatic.com https://i.ytimg.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://www.gstatic.com;
      font-src 'self' data: https://fonts.gstatic.com https://www.gstatic.com;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com https://apis.google.com https://www.googleapis.com https://*.firebaseapp.com https://cdn.jsdelivr.net;
      script-src-elem 'self' 'unsafe-inline' 'unsafe-eval' https://www.google.com https://www.gstatic.com https://apis.google.com https://www.googleapis.com https://*.firebaseapp.com https://cdn.jsdelivr.net;
      frame-src 'self' https://www.google.com https://www.gstatic.com https://www.youtube.com https://youtube.com https://*.firebaseapp.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
    
    # Permissions Policy
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para imágenes
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# No cache para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
